on: push
defaults:
  run:
    shell: bash
jobs:
  whatever_event:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ran because of some event
        echo github.event_name: ${{ github.event_name }}
        echo github.event.action: '${{ github.event.action }}' # "opened" when PR is opened, then "" if pushing commits to the PR, then "closed" when PR is closed
        echo github: '${{ toJSON(github) }}'

  compute_project:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install Node Dependencies
      run: cd compute-project && npm install

    - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Fastly Version
      run: fastly version

    - name: Serve Compute Package
      run: fastly compute serve --dir compute-project --watch --verbose
