# If someone with write access comments "/ok-to-test sha=<SHA>" on a pull request, emit a repository_dispatch event
# The PAT (Personal Access Token) OK_TO_TEST_DISPATCH_TOKEN needs either `repo` or `public_repo` scope.
name: Ok To Test
on:
  issue_comment:
    types: [created]
jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }} # ignore issue comments
    steps:
      - name: Trigger test run for forked PR
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.OK_TO_TEST_DISPATCH_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: ok-to-test
          permission: write
