# name: Reusable Workflow
# on:
#   workflow_call:
#     inputs:
#       matrix:
#         required: true
#         type: string
#       foo:
#         required: true
#         type: string
#       bar:
#         type: number
#       baz:
#         type: boolean
#
# jobs:
#   my_reusable_job:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix: ${{ fromJSON(inputs.matrix) }}
#     steps:
#       - if: ${{ matrix.FOO != 'abc' }}
#         run: echo "matrix.FOO is NOT set" && exit 1
#       - run: echo ${{ inputs.matrix }}
#       - run: echo ${{ matrix.FOO }}
#       - run: echo ${{ matrix.BAR }}
#       - run: echo ${{ inputs.foo }}
#       - run: echo ${{ inputs.bar }}
#       - run: echo ${{ inputs.baz }}
