on: push
jobs:
  pushed_event:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - uses: ./.github/actions/debug
      with:
        destroy: true
    - uses: ./.github/actions/debug
      with:
        destroy: "true"
    - uses: ./.github/actions/debug
      with:
        destroy: false
    - uses: ./.github/actions/debug
      with:
        destroy: "false"
    - uses: ./.github/actions/debug
    - run: go version
    - run: echo "$PATH"
    - run: touch foo.txt && sudo cp foo.txt /usr/local/bin/foo.txt
    - run: ls /usr/local/bin/
    - run: make bin-viceroy
