on: push
jobs:
  pushed_event:
    runs-on: ubuntu-latest
    outputs:
      continue: "true"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - uses: ./.github/actions/debug
      with:
        destroy: true
    - uses: ./.github/actions/debug
      with:
        destroy: "true"
    - uses: ./.github/actions/debug
      with:
        destroy: false
    - uses: ./.github/actions/debug
      with:
        destroy: "false"
    - uses: ./.github/actions/debug
    - run: echo "foo=\"$(date +"%s")\""
    - run: go version
    - run: echo "$PATH"
    - run: touch foo.txt && sudo cp foo.txt /usr/local/bin/foo.txt
    - run: ls /usr/local/bin/
    - run: make bin-viceroy
    - run: echo foobar > some_file.txt
    - run: cat some_file.txt

  job2:
    needs: pushed_event
    outputs:
      workspace_id: ${{ steps.gen-id.outputs.workspace_id }}
    runs-on: ubuntu-latest
    if: ${{ needs.pushed_event.outputs.continue == 'true' }}
    steps:
      - run: echo "job2 was run"
      - id: gen-id
        run: echo "workspace_id=123" >> $GITHUB_OUTPUT

  job3:
    needs: job2
    runs-on: ubuntu-latest
    if: ${{ needs.job2.outputs.workspace_id != '' }}
    steps:
      - run: echo "job3 was run"
      - run: echo ${{ needs.job2.outputs.workspace_id }}
