name: Testing GitHub Actions on Windows
on: [push]
concurrency: # cancel in progress runs on push
  group: "windows-test"
  cancel-in-progress: true
jobs:
  testing-finding-of-files:
    runs-on: windows-latest
    steps:
      - run: mkdir -p foo\bar
      - run: Get-ChildItem -Force -recurse
      - run: ni .\foo\bar\main.go
      - run: where /r foo *.go
